### ISSUE TITLE
프론트엔드 개발자님들을 위한 Access Token과 Refresh Token 정리!

### ISSUE THREAD

**Issue by iamkanguk97** [Team-C7Z/Mappilogue_Server#12]
안녕하세요! 저희가 저번에 토큰 관련해서 회의를 했을 때 Refresh Token은 사용해보지 않으셨다고 하신 것 같아서 조금이나마 도움(?)이 되고자 설명글을 조금 적어보려고 합니다 하하 :)

저도 잘 몰라서 여러분들께 최대한 정확한 지식을 전달드리고자 여러 글을 많이 찾아봐서 개념을 잡고자 노력하고 있습니다.. 이쁘게 봐주십쇼!

### 참고한 자료
- [JWT 토큰 인증 이란? (쿠키 vs 세션 vs 토큰)](https://inpa.tistory.com/entry/WEB-%F0%9F%93%9A-JWTjson-web-token-%EB%9E%80-%F0%9F%92%AF-%EC%A0%95%EB%A6%AC)
- [JWT에서 Refresh Token은 왜 필요한가?](https://velog.io/@park2348190/JWT%EC%97%90%EC%84%9C-Refresh-Token%EC%9D%80-%EC%99%9C-%ED%95%84%EC%9A%94%ED%95%9C%EA%B0%80)

### 간단한 설명
아마 위에 제가 올려드린 두 링크를 한번 읽어보시면 쿠키, 세션 그리고 JWT에 대한 개념이 어느정도 정리는 될 것이라고 생각합니다. 2번째 링크에서는 JWT Refresh Token을 사용하는 이유에 대해서 잘 정리가 되어있으니까 한번 확인해주시면 감사하겠습니다!

실무에서는 토큰 방식보다 세션 방식을 주로 사용한다고 들어서 세션 방식을 사용해볼까? 하다가 저희가 지금은 조그마한 서비스를 구현하고 있고 빠른 개발이 필요한 시점이라서 JWT를 선택하게 되었습니다!

간단하게 말해서 Refresh Token은 Access Token을 갱신하기 위한 토큰으로만 사용된다고 알고 계시면 됩니다. 서버쪽에서는 Access Token 유효기간을 설정할 수 있는데 너무 짧게 설정하면 앱에서 계속해서 로그인을 요구하는 메세지가 발생할 것이고, 너무 길게 사용하면 보안상으로도 문제가 발생할 수 있습니다. 

그래서 Access Token의 유효시간을 적당하게 짧게 설정하게 됩니다. 그리고 Access Token이 만료되면 가지고 있던 Refresh Token으로 Access Token을 새로 갱신해주는 겁니다. 그렇게 되면 Access Token이 만료되어도 바로 새로 발급받아서 서비스를 사용할 수 있기 때문에 이전 방식보다는 조금 더 보안이 강화된 셈이라고 생각합니다. (하지만 이 방법도 취약점이 있긴 합니다!)

### 그러면 우리(클라이언트)는 강욱님이 개발하신 토큰 갱신하기 API를 어떻게 사용해야 하나요?
API 시트를 확인해보시면 얼추 흐름을 확인하실 수 있지만 제가 생각한 로직을 간단하게 말씀드리자면..

> (1) Access와 Refresh 모두 만료된 경우: 새로 `소셜로그인 API`를 호출하셔야 합니다.
> (2) Access 또는 Refresh만 만료된 경우: 각 토큰을 새로 발급받아서 response로 보내드립니다.
> (3) 두 토큰 모두 만료되지 않은 경우: 두 토큰 모두 정상이라고 response를 보냅니다.

제가 클라이언트 부분은 작업해본적이 없어서 자세히는 모르겠지만 조금 찾아보니까 특정 이벤트가 발생하면 자동으로 API를 호출할 수 있도록 설계할 수 있다고 본 것 같은데 이 부분은 한번 확인해주시고 말씀해주시면 감사하겠습니다!

---
도움이 되셨을지는 모르겠습니다! 저는 거의 24시간 연락이 오픈되어 있으니 언제나 개발하시다가 제가 잘못된 부분이 있는 것 같거나 궁금하신 점이 있다면 언제든 디스코드나 카톡으로 연락주십쇼!

제가 이 인증 관련한 내용들을 지금 블로그에 공부하면서 정리중인데 블로그 작성이 끝나면 또 공유드리겠습니다..ㅎ
저희 릴리징까지 화이팅입니다!!!

**Comment by ChunBaee** [comment]
제가 알기로는..
AccessToken 만료 -> RefreshToken을 보내고 새로운 AccessToken 받기 -> 받은 AccessToken으로 다시 API 호출
RefreshToken 만료 -> 재로그인 요청 -> AccessToken, RefreshToken 모두 받기
인데.. 
만약 사용자가 사용 중 RefreshToken (제이슨이 생각하신 AccessToken, RefreshToken 모두 만료) 면, 모든 동작을 무시하고 로그인 화면을 보여주는게 맞는지? 는 생각을 좀 해봐야 할 것 같습니다 ㅠ

**Comment by Jiwon116** [comment]
글 잘 봤습니다!!

춘배님이 말씀하신 상황(사용자가 사용 중에 access, refresh 모두 만료)은 생기지 않을 것 같아요..! 저희가 사용중일때 계속 토큰을 확인하는게 아니라 _로그인 시에만 토큰이 유효한지 확인_ 하니까요!! 
만약 사용 중에 모든 토큰이 만료됐다면, 다음에 앱을 켰을 때 사용자에게는 '로그인 인증이 만료되었다' 와 같은 메세지로 알린 후 로그인 화면으로 돌아가 토큰을 재발급 받는게 맞다고 생각합니다!

제가 참고한 자료 추가하겠습니다! 
https://inpa.tistory.com/entry/WEB-%F0%9F%93%9A-Access-Token-Refresh-Token-%EC%9B%90%EB%A6%AC-feat-JWT#thankYou
https://mccoy-devloper.tistory.com/59

**Comment by ChunBaee** [comment]
로그인시에만 토큰을 확인하는게 아니라, JWT를 사용하는 방식으로는 회원 전용 서비스 (로그인을 해야만 사용 가능한 서비스)의 API를 호출할 때 클라이언트가 JWT(AccessToken)를 담아서 보내고, 서버측에서 그 토큰의 유효성을 검증한 후 Response를 보내주는 방식이라, 사용중일 때 API를 호출할 때 마다 AccessToken을 검증하니 사용중에 만료되는 일이 생길 수 있다고 생각했었습니다.
만약 매 API마다 토큰의 유효성을 확인하지 않는다면 누구나 API 주소만으로도 우리 서비스의 회원 정보같은 노출되면 안 되는 Response 내용들을 탈취 해갈 수 있으니까요

**Comment by iamkanguk97** [comment]
<2023.07.05 수요일 회의내용 정리>

- 위의 정리된 로직대로 진행하면 약 2주마다 앱에서 '세션이 만료되어서 다시 재로그인을 요구' 같은 문구가 발생하기 때문에 사용자 측면에서 불편할 것으로 생각함. 은행 어플 같은 보안이 중요한 앱 같은 경우에는 그럴 수 있지만 카카오톡, 인스타 같은 앱을 사용했을 때 한번도 재로그인을 요구한적이 없다.
- 따라서 재로그인 로직을 빼고 해당 API를 수정하기로 결정!

- 토큰 갱신하기 API에서는 header에 refresh-token만 보내는 것으로 결정. access-token을 굳이 보내지 않아도 괜찮을 것 같다고 결정.
- 해당 API가 호출되면 Access Token은 새로 갱신해서 Return. refresh-token은 만료확인 후 만료가 되었으면 새로운 refresh-token 발급 그렇지 않으면 클라이언트로부터 받은 refresh-token 그대로 발급.

**Comment by iamkanguk97** [comment]
<2023.08.15 로직 일부 수정>

Redis에 들어있는 값과 사용자가 요청한 Refresh Token을 비교해서 서로 동일한지 확인.
하지만 만약 Redis에 사용자의 RT가 없으면? 만료되었다는 의미인데?
이것은 사용자가 2주동안 앱을 아예 사용하지 않은 경우에는 한번도 토큰 갱신을 한 적이 없다는 의미이다. 따라서 이럴 경우에는 재로그인을 요하는게 맞지 않나라는 생각이 든다.
